### ISSUE TITLE
MED_HOSP_CNT  field definition

### ISSUE THREAD

**Issue by bjeffrey92** [amacali/covidlive#1]
Hi, thanks for putting this resource together. 

I have a question about the definition of the `MED_HOSP_CNT` field in your data, is this all patients admitted to a hospital including those captured in the `MED_ICU_CNT` and `MED_VENT_CNT` fields?

**Comment by ChrisJollyAU** [comment]
Yep. That is normally how the states report it. For example take NSW, latest statistics page has "There are currently 1,582 COVID-19 cases admitted to hospital, including 71 people in intensive care, 23 of whom require ventilation."
So `MED_HOSP_CNT` will be 1582, `MED_ICU_CNT` is 71 and `MED_VENT_CNT` will be 23

**Comment by amacali** [comment]
As Chris has explained, the ICU is a subset of HOSP.
Vent is a subset of ICU.

**Comment by bjeffrey92** [comment]
Great, thank you for clarifying that
